### ISSUE TITLE
Switch doesnt working

### ISSUE THREAD

**Issue by ecsdantas** [TINYT1ME/LogicCircuit#1]
Just tried to click on middle of switch but its not changing its status.

How i can fix it?

**Comment by TINYT1ME** [comment]
I stopped uploading the latest changes to pypi, so if you are using pip to install it will not be using the latest version. If you are downloading directly from the repo than it should be working, have you tried using a mouse and pressing on the scroll wheel button while hovering over a switch?

Lmk if it still does not work

**Comment by ecsdantas** [comment]
WoW

Mouse scroll button works properly!

Thank you very much!
